name: "🐄 module"
description: >
  A module report can be a request for a new data source module or an issue or an issue or behavior that's unexpected or differs from specific module documentation.

labels:
  - "module"

body:
  - type: "textarea"
    attributes:
      label: "Module Request or Issue"
      description: "The name of the module in question, or a suggested name for a new Module.
      Any information you have on the module or the desired remote API in question."
    validations:
      required: true

